name: main-pipeline

on: 
  pull_request:
    branches:
      - main

jobs:  
  main-pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
  
      - name: Setup .NET Core SDK 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      
      - name: Add GitHub Packages Source
        run: dotnet nuget add source https://nuget.pkg.github.com/ricardogoes/index.json -n github -u ${{secrets.GH_USERNAME}}  -p ${{secrets.GH_TOKEN}} --store-password-in-clear-text

      - name: Install dependencies
        run: dotnet restore
      
      - name: Build API
        run: dotnet build --configuration Release --no-restore
              
      - name: Run unit tests
        run: dotnet test ./tests/Odin.Auth.UnitTests/Odin.Auth.UnitTests.csproj --no-restore --verbosity normal

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Dockerhub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ricardoduquegoes/odin-auth-api:latest
          