name: push

on: 
  workflow_run:
    workflows: build and test
    branches: main
    types: completed

jobs:
  push:
    runs-on: ubuntu-latest
    needs: build-and-test

    if: github.ref == 'refs/heads/main'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Dockerhub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ricardoduquegoes/odin-auth-api:latest
